name: fruit_pop
description: Fruit Pop - 과일 합치기(수이카 스타일) 게임
publish_to: 'none'
version: 1.0.1+5

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.18.0
  flame_forge2d: ^0.18.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.1.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  advertising_id: ^2.7.1
  app_tracking_transparency: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/audio/

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#FFE5F1"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#FFE5F1"
    theme_color: "#FF8FB1"
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256
